project:
  type: sverto
  # pre-render:
  #   - './copy-extension.sh'
  
execute:
  freeze: auto

website:
  navbar:
    background: "#222222"
    search: true
    left:
      - text: "Sverto"
        file: index.qmd
      - text: "Examples"
        menu:
          - text: "Simple bar chart"
            file: examples/barchart/index.qmd
          - text: "Time series chart"
            file: examples/time-series/index.qmd
      - text: Changelog
        file: news.qmd
      # - about.qmd
    right:
      - icon: github
        href: https://github.com/jimjam-slam/sverto

format:
  html:
    title-block-banner: true
    theme: [default, style.scss]
    linkcolor: "#36a7e9"
    callout-appearance: simple
    
