project:
  type: website
  
execute:
  freeze: auto

website:
  announcement:
    icon: stars
    dismissable: true
    type: success
    position: above-navbar
    content: "Sverto is now quarto-svelte — and it supports Svelte 5! [**Learn how to migrate to the new version.**](/articles/migrating-from-sverto-v1){style=\"color: var(--bs-text-success)\"}"
  navbar:
    background: "#222222"
    search: true
    left:
      - text: "quarto-svelte"
        file: index.qmd
      - text: Examples
        menu:
          - text: "Simple bar chart"
            file: examples/barchart/index.qmd
          - text: "Time series chart"
            file: examples/time-series/index.qmd
      - text: Articles
        menu:
          - text: Migrating from Sverto v1 and Svelte 3
            file: articles/migrating-from-sverto-v1
          - text: Default prop values
            file: articles/default-prop-values/index.qmd
      - text: News
        file: news.qmd
    right:
      - icon: github
        href: https://github.com/jimjam-slam/quarto-svelte

format:
  html:
    title-block-banner: true
    theme: [default, style.scss]
    # linkcolor: "#36a7e9"
    callout-appearance: simple
    
