project:
  type: website
  
execute:
  freeze: auto

website:
  navbar:
    background: "#222222"
    search: true
    left:
      - text: "Sverto"
        file: index.qmd
      - text: Examples
        menu:
          - text: "Simple bar chart"
            file: examples/barchart/index.qmd
          - text: "Time series chart"
            file: examples/time-series/index.qmd
      - text: Articles
        menu:
          - text: Default prop values
            file: articles/default-prop-values/index.qmd
      - text: News
        file: news.qmd
    right:
      - icon: github
        href: https://github.com/jimjam-slam/sverto

format:
  html:
    title-block-banner: true
    theme: [default, style.scss]
    linkcolor: "#36a7e9"
    callout-appearance: simple
    
