# workflow to test quarto-svelte

on:
  workflow_dispatch:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

name: quarto-svelte-check

jobs:
  quarto-svelte-check:
    
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    
    runs-on: ${{ matrix.os }}
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.5.25

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install quarto-svelte docs npm dependencies
        run: npm install
        working-directory: ./docs

      - name: Create docs _extensions folder
        run: mkdir docs/_extensions
        shell: bash

      - name: Copy quarto-svelte extension into docs 
        run: cp -rf _extensions/quarto-svelte docs/_extensions/quarto-svelte
        shell: bash

      - name: Render quarto-svelte docs
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: docs
