# workflow to test quarto-svelte

on:
  workflow_dispatch:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

name: quarto-svelte-check

jobs:
  quarto-svelte-check:
    
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    
    runs-on: ${{ matrix.os }}
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.5.25

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Copy quarto-evelte extension; run npm install
        run: ./copy-extension.sh
        working-directory: ./docs
        shell: bash

      - name: List copied extension dir contents
        run: ls -a _extensions/quarto-svelte
        working-directory: ./docs

      # - name: Render quarto-svelte docs
      #   uses: quarto-dev/quarto-actions/render@v2
      #   with:
      #     path: docs

      - name: Render quarto-svelte docs (manually)
        run: quarto render
        working-directory: ./docs

      - name: Verify that compiled Svelte .js bundles are present
        run: |
          test -f docs/_site/Circles.js &&
          test -f docs/_site/examples/barchart/BarChart.js &&
          test -f docs/_site/examples/time-series/TimeSeriesChart.js
